### ISSUE TITLE
Change Society of Accounting Line Items

### ISSUE THREAD

**Issue by garretthav** [matttarantino/transact#41]
Copy and pasted from their email:

"Therefore, would you be able to delete or disregard:
1.) National Conference, August 8th at 8:16am
2.) SAS Dinner at April 26th 1.:23 pm

Also we were not able to edit the line items for National Conference, August 8th at 9am:
1.) The  hotel total requested budget should be $298, instead of $894
2.) Please disregard or delete the flight information, as we would most likely drive"

**Comment by matttarantino** [comment]
Fixed
